name: test every commit
on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install libsecp256k1-dev
        run: sudo apt-get install libsecp256k1-dev

      - uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - run: go test ./...
